### PR TITLE
#150 Fix: Added default environment values as failover.

### PR DESCRIPTION
**Pull request by vaishnochaitanya**
Used [posix parameter expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html) to mitigate the problem incase if system is unable to read the environment variables defined in .env file.

### CODE REVIEW

**Comment by righel** [comment]
Looks good, would you mind changing the default timezone from `Asia/Calcutta` to `UTC`? I can merge it then.

**Comment by vaishnochaitanya** [comment]
Sure. I have updated the default TIMEZONE value as per template.env file.

**Comment by vaishnochaitanya** [comment]
@righel does the fix require any other change?

**Comment by righel** [comment]
Thanks a lot!

**Pull request merged**
