### PR TITLE
Dockerfile update

### PR DESCRIPTION
**Pull request by challs**
Hi there

These changes reduce the complexity of the Dockerfile and number of interim images created. The functionality itself is unchanged so this should simply work for anyone who already has the images building properly.

### CODE REVIEW

**Comment by coolacid** [comment]
Would you be willing to test with new bases? 
- ubuntu:bionic (to keep in line with current build)
- debian:buster-slim (to slim down the size and only have base requirements)

**Comment by adulau** [comment]
Could you rebase to the current version of misp-docker to resolve the conflict? Thanks a lot.

**Comment by challs** [comment]
> Could you rebase to the current version of misp-docker to resolve the conflict? Thanks a lot.

I've merged all the changes in and pushed to the branch.

(Note I'm not able to test a complete build yet because of the speed of my internet connection.)

**Comment by challs** [comment]
> Would you be willing to test with new bases?
> 
> * ubuntu:bionic (to keep in line with current build)
> * debian:buster-slim (to slim down the size and only have base requirements)

I did some testing with Bionic and managed to get a build. You can find the changes I needed at https://github.com/challs/misp-docker/commit/348b89128b701a9c1375cd175f659f7b04242679

**Comment by challs** [comment]
> (Note I'm not able to test a complete build yet because of the speed of my internet connection.)

I've now checked the build. It turns out that `misp-modules` recently introduced a dependency on `apiosintDS`, but this is not available on Xenial so the build fails. The problem does not show up on current `master` because of #62.

I worked around the issue in eacda8f. The workaround can be removed by moving to a newer base image.

I confirm that this pull request also closes #62

**Comment by adulau** [comment]
Could you rebase with the current HEAD? and update the pull-request? Thanks a lot.

**Comment by challs** [comment]
> Could you rebase with the current HEAD? and update the pull-request? Thanks a lot.

Thanks for merging some of my changes. I will open separate PRs for the remaining items, since they are mostly unrelated to each other now.

**Pull request closed without merging**
